[package]
name = "wobl"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
device_query = "4.0.1"

[dependencies.sdl2]
version = "0.38.0"
default-features = false
features = ["ttf"]



[features]
default = []
crossterm_events = []

